name: hparker-ml-zoomcamp-2025

services:
  homework:
    image: hparker-ml-zoomcamp-2025/homework
    build:
      context: ../homework
      dockerfile: ../docker/Dockerfile.jupyter
      target: homework
    volumes:
      - ../homework:/home/hparker/homework
    ports:
      - 6592:8888
  hw05:
    image: hparker-ml-zoomcamp-2025/homework-05
    build:
      context: ../homework/05
      dockerfile: ../../docker/Dockerfile.hw05
    ports:
      - 9696:9696
  midterm:
    image: hparker-ml-zoomcamp-2025/midterm
    build:
      context: ../midterm
      dockerfile: ../docker/Dockerfile.jupyter
      target: midterm
    volumes:
      - ../midterm:/home/hparker/midterm
    depends_on:
      - midterm-service
    ports:
      - 6593:8888
  midterm-service:
    image: hparker-ml-zoomcamp-2025/midterm-service
    build:
      context: ../midterm
      dockerfile: ../docker/Dockerfile.midterm
    ports:
      - 9696:9696

